### ISSUE TITLE
No HTTPS support because HTTP hardcoded

### ISSUE THREAD

**Issue by anateus** [nicolaisi/couchquery#10]
The class Httplib2Client uses 'http://' directly, this cases https not to work (e.g. with Cloudant).

Locally I've monkeypatched it to use a variable called protocol, i.e. s/'http:\/\/'/protocol/g with:

```
if '@' in self.uri:
  protocol = 'https://' if 'https' in self.uri else 'http://'
```

**Comment by nicolaisi** [comment]
This is supported now.

**Comment by nicolaisi** [comment]
I'm not sure whether this is generally fixed with the commit from @anateus will leave this open

**Comment by nicolaisi** [comment]
Tested on iriscouch with https. So far, it is passing all the tests.
