### ISSUE TITLE
id is not quoted in couchquery.Database.get

### ISSUE THREAD

**Issue by NiltonVolpato** [nicolaisi/couchquery#12]
(and possibly other relevant places)

```
>>> db = couchquery.Database(...)
>>> db.get('/bar')
...
... CouchDBDocumentDoesNotExist: No document at id /bar
```

But a /bar does exist. It should be sending a request with "%2Fbar" but the method fails to correctly quote its argument.

**Comment by nicolaisi** [comment]
This sounds a bit weird. When you create a document on the database, the document will automatically be assigned an id, i.e. 65028e54e848b7b022e98d1ae506946e

I reporduce your problem and it seems it is not handling the "/" character well. 

We need to do URL encoding I guess.

This works:

```
In [32]: db.get('%2Fbar')
Out[32]: 
{'_id': '/bar',
 '_rev': '2-85f013ce0f2d0ab71bf2bb9563e8879d',
 'name': 'John Whorfin',
 'type': 'red-lectroid'}
```

**Comment by nicolaisi** [comment]
https://github.com/nicolaisi/couchquery/commit/b73e8a8c39ffef4a75df4a023fc8d61eb2ed0d5e

Added url encode. Now you can call db.get('/bar')

You can even do this :)

```
In [4]: db = couchquery.Database("http://admin:foobar@localhost:5984/modules")

In [5]: db.get('bär')
Out[5]: 
{'_id': u'b\xe4r',
 '_rev': '3-e857db9fe3437798e541e31f11483b62',
 'name': 'Nicholas'}
```

**Comment by nicolaisi** [comment]
This is fixed.
