### ISSUE TITLE
createdb() fails to return an "error" response

### ISSUE THREAD

**Issue by nickperkinslondon** [nicolaisi/couchquery#13]
createdb() includes the following:
assert response.status == 201
...which causes an exception without returning the response body, which in my case was:
str: {"error":"unauthorized","reason":"You are not a server admin."}
If the create db fails, you should still return the reponse, so the caller gets the "reason".

**Comment by nicolaisi** [comment]
good catch. It does not raise any exception when it hits error. I'd implemented a raise exception here when the response status is not 200/201 for createdb and also deletedb

https://github.com/mikeal/couchquery/pull/19
