### ISSUE TITLE
createdb() does not use credentials

### ISSUE THREAD

**Issue by nickperkinslondon** [nicolaisi/couchquery#14]
the following line of code:
`resp = couchquery.createdb('http://nick:banana@localhost:5984/test_couchquery')`

...results in the following request:
`PUT http://localhost:5984/test_couchquery/`

Somewhere along the way, the "credentials" get lost, and are never sent to CouchDB.

**Comment by nicolaisi** [comment]
```
In [19]: db = couchquery.createdb('http://localhost:5984/forms2')
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)

----> 1 db = couchquery.createdb('http://localhost:5984/forms2')

    335         db = Database(arg)
    336     response = db.http.put('')
--> 337     assert response.status == 201
    338     return json.loads(response.body)
    339 

AssertionError: 
```

When I send the correct credential, then I can successfully create the database.

```
In [20]: db = couchquery.createdb('http://admin:foobar@localhost:5984/forms2')
```

It does not seem like the credential went missing.

**Comment by nicolaisi** [comment]
I don't see any issue here. If the Database is restricted to only verified user, you could not create database without your credential. Maybe helpful to give more information to reproduce this issue.
