### ISSUE TITLE
sync_design_doc() does not use credentials

### ISSUE THREAD

**Issue by nickperkinslondon** [nicolaisi/couchquery#15]
sync_design_doc() does not use credentials

`db = cq.Database('http://nick:banana@localhost:5984/test_couchquery')
resp = db.create({'name':'Nick','age':42})
if resp.get('ok'): print 'saved doc'     # <------  this works
db.sync_design_doc('banzai', views_dir) # <----- this does not`

I can save a doc, but can not sync_design_doc:

`couchquery.CouchDBException: {"error":"unauthorized","reason":"You are not a db or server admin."}`

**Comment by nicolaisi** [comment]
I cannot reproduce this.

I can successfully sync my document using the correct credentials.
