### ISSUE TITLE
compact is missing

### ISSUE THREAD

**Issue by dickkniep** [nicolaisi/couchquery#31]
Currently there is no "compact" method. Also the command 

result = db.http.post(self.dbConnection.uri + '_compact')

yields a faulty result

**Comment by nicolaisi** [comment]
I think it makes sense to add a compact method here. I'm working on it.

**Comment by nicolaisi** [comment]
Hi Dick,

I had implemented the compaction method, and also a test code for this. Note that you need to give your DB some time to do the compaction depending on how large your database is.

you can just do this:

```
self.db.compaction()
```

it returns true if successful, else false.

I had also release this under 0.10.2, so you can easily update your couchquery to get this feature.

commit: 79f435c09142e4d8bdd62b163fccdaaa0015642d

**Comment by dickkniep** [comment]
Hi Nicholas,

Thanks a lot. I will incorporate this in my script!!

Met vriendelijke groet,
Dick Kniep
Lindix BV
tel. 036-5215580
mob. 06-50991858

-----Oorspronkelijk bericht-----
Van:    Nicholas TJ notifications@github.com
Verzonden:  do 14-08-2014 17:37
Onderwerp:  **SPAM** Re: [couchquery] compact is missing (#31)
Aan:    nicolaisi/couchquery couchquery@noreply.github.com; 
CC: Dick Kniep dick@lindix.nl;
