### ISSUE TITLE
Add filters to design document also

### ISSUE THREAD

**Issue by dickkniep** [nicolaisi/couchquery#32]
Currently it is possible to get views from a map inside the source tree, it would be very nice to have the possibility to add filters also to design documents.

So with a map called "filters" and then the name and next a filter.js where the actual filter is stored.

**Comment by nicolaisi** [comment]
are you referring to this? http://nicolaisi.github.io/couchquery/#creating-views

I think what you are mentioning here is already implemented. 

I'm not very sure whether this still works or not, it use to work, but if I last recall, it has some problem. I can look into this if you can reproduce the error and I'll fix it.

**Comment by dickkniep** [comment]
Hi Nicolai,

No it is not the same. Within design documents one can have views and one can have filters. Both can be present and have specific purposes. For instance when using Couchdb (as we are doing) one can filter certain documents with a filter from a design document. Much like, but not the same as a view. 

See also: http://guide.couchdb.org/draft/notifications.html The section at the end about filters.

Met vriendelijke groet,
Dick Kniep
Lindix BV
tel. 036-5215580
mob. 06-50991858

-----Oorspronkelijk bericht-----
Van:    Nicholas TJ notifications@github.com
Verzonden:  do 21-08-2014 15:24
Onderwerp:  Re: [couchquery] Add filters to design document also (#32)
Aan:    nicolaisi/couchquery couchquery@noreply.github.com; 
CC: Dick Kniep dick@lindix.nl;

**Comment by nicolaisi** [comment]
At a quick glance, it looks like a map reduce function, but I'll read in detail about the filter section and get back to you soon.

**Comment by dickkniep** [comment]
Hi Nicholas,

Thanks a ton!

Met vriendelijke groet,
Dick Kniep
Lindix BV
tel. 036-5215580
mob. 06-50991858

-----Oorspronkelijk bericht-----
Van:    Nicholas TJ notifications@github.com
Verzonden:  do 21-08-2014 16:12
Onderwerp:  Re: [couchquery] Add filters to design document also (#32)
Aan:    nicolaisi/couchquery couchquery@noreply.github.com; 
CC: Dick Kniep dick@lindix.nl;

**Comment by nicolaisi** [comment]
Hi Dick,

I had implemented the filters feature and release a beta 0.10.3

I tried to implement this so that user can have the maximum flexibility, but I have no experience in using this, so I need a little feedback on this feature.

I created a folder called filters and another folder called "red" and inside this folder a js file called filter.js
https://github.com/nicolaisi/couchquery/tree/master/tests/filters/red

as usual, you can update your couchquery from pypi and it should work as follows:

```
In [1]: import couchquery

In [2]: BASE_URI = 'http://localhost:5984/'

In [3]: URI = BASE_URI + 'couchquery_unittest'

In [4]: db = couchquery.Database(URI)

In [5]: db.sync_design_doc('banzai', os.path.join(this_dir, 'filters'), filters=True)

In [6]: rows = db.filters.banzai.red()

In [7]: rows.seq()
Out[7]: [13, 17]

In [8]: rows.ids()
Out[8]: ['b2d06b0bd1e03db9cd0794ed2081020c', 'b2d06b0bd1e03db9cd0794ed20811f6d']

In [9]: rows.changes()
Out[9]: 
[[{'rev': '1-7f7a182c6db05e0b7d7bb6c09591dfd7'}],
[{'rev': '1-83b80c95aea870257bb47da00a530ae3'}]]

In [10]: rows.last_seq()
Out[10]: 21
```

I only implemented the first section of the changes filters, please help check if this is ok. If so, I'll continue with accepting a request parameter.

Cheers,
Nicholas

**Comment by dickkniep** [comment]
Hi Nicholas,

It has taken a while before I could react to your swift adoption of my request. I thank you very much. I have not been able to use it sofar, but I will most certainly start experimenting with it in the coming month. 

Furthermore I have stumbled upon something weird. I tried to use the delete function with a list of json objects. However then I get a response of 500, which basicly says that I have screwed up my json. However, this JSON is generated using a view and it is VERY simple Json:

[{'per_id':9514,'_id':'Clienten_9514','_rev':'5-81d214ccaabcec35b731dd3936af385f'}]

When I try the same without the list, but simply the object, I don't get any error, but the row is not deleted....

Met vriendelijke groet,
Dick Kniep
Lindix BV
tel. 036-5215580
mob. 06-50991858

-----Oorspronkelijk bericht-----
Van:    Nicholas TJ notifications@github.com
Verzonden:  ma 25-08-2014 16:08
Onderwerp:  Re: [couchquery] Add filters to design document also (#32)
Aan:    nicolaisi/couchquery couchquery@noreply.github.com; 
CC: Dick Kniep dick@lindix.nl;

**Comment by dickkniep** [comment]
Hi Nicholas,

I found what is happening with the delete. The object must be the same as the actual document that is to be deleted. So it is not enough to have the _id and the _rev.

Is this a safety feature?

Met vriendelijke groet,
Dick Kniep
Lindix BV
tel. 036-5215580
mob. 06-50991858

-----Oorspronkelijk bericht-----
Van:    Nicholas TJ notifications@github.com
Verzonden:  ma 25-08-2014 16:08
Onderwerp:  Re: [couchquery] Add filters to design document also (#32)
Aan:    nicolaisi/couchquery couchquery@noreply.github.com; 
CC: Dick Kniep dick@lindix.nl;

**Comment by nicolaisi** [comment]
Hi Dick,

does this "delete" has anything to do with this filter?

base on your text, I would say, no, that is not normal, with an _id and a _rev, one should be able to delete a document, object is just another way of representing the current state and at the same time provides a mean to delete it.

i think this has nothing to do with this filter right? If so, can you reproduce this and I will look into this on a new issue ticket.

**Comment by dickkniep** [comment]
Hi Nicholas,

No, the delete has nothing to do with the filters.

I will try to device a simple test that demonstrates the problem.... (But it will take some time as I am currently swamped by the last tests before production!!)

Met vriendelijke groet,
Dick Kniep
Lindix BV
tel. 036-5215580
mob. 06-50991858

-----Oorspronkelijk bericht-----
Van:    Nicholas TJ notifications@github.com
Verzonden:  wo 10-09-2014 10:53
Onderwerp:  Re: [couchquery] Add filters to design document also (#32)
Aan:    nicolaisi/couchquery couchquery@noreply.github.com; 
CC: Dick Kniep dick@lindix.nl;

**Comment by nicolaisi** [comment]
Sure thing, take your time, looking forward to fix that "weird delete" feature :smile:
