### ISSUE TITLE
Problem with changes 

### ISSUE THREAD

**Issue by dickkniep** [nicolaisi/couchquery#35]
I use the changes module that you have added. This works OK if couchdb is in admin party mode. However, when I switch off the admin party mode, I get an error.

> > > c =httplib.HTTPConnection(u.netloc)
> > > t = c.request('GET',u.path)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/httplib.py", line 973, in request
> > >     self._send_request(method, url, body, headers)
> > >   File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
> > >     self.endheaders(body)
> > >   File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
> > >     self._send_output(message_body)
> > >   File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
> > >     self.send(msg)
> > >   File "/usr/lib/python2.7/httplib.py", line 791, in send
> > >     self.connect()
> > >   File "/usr/lib/python2.7/httplib.py", line 772, in connect
> > >     self.timeout, self.source_address)
> > >   File "/usr/lib/python2.7/socket.py", line 553, in create_connection
> > >     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
> > > socket.gaierror: [Errno -2] Name or service not known

I have tried the exact statements from the python console and I get this error (which is the error that is produced by the script) So obviously something is going wrong there, but I have no idea what is going on. Could you take a look?

**Comment by nicolaisi** [comment]
I'll take a look into this

**Comment by dickkniep** [comment]
Hi Nicolas,

I found the problem.

urlparse.netloc is used for the HTTPconnection to the database and it contains the userid and password if couchdb is not in admin party mode. That causes the crash.

So the connection to the database should be cleaned from the user/password bit. (so urlparse.netloc cannot be used without some cleaning)

For instance:

```
    if parsed_uri.username:
        netloc = parsed_uri.netloc.split('@')[1]
    else:
        netloc = parsed_uri.netloc
```

Met vriendelijke groet,
Dick Kniep
Lindix BV
tel. 036-5215580
mob. 06-50991858

-----Oorspronkelijk bericht-----
Van:    Nicholas TJ notifications@github.com
Verzonden:  do 22-01-2015 18:08
Onderwerp:  Re: [couchquery] Problem with changes  (#35)
Aan:    nicolaisi/couchquery couchquery@noreply.github.com; 
CC: Dick Kniep dick@lindix.nl;

**Comment by nicolaisi** [comment]
Thanks for the workaround, I'll try to fix this in the source ^^

**Comment by dickkniep** [comment]
Changes do not work when not in admin party. Even  with the workaround as mentioned I get a 401. So this is a real problem.
