### ISSUE TITLE
sync_design_doc() should ignore directories starting with .

### ISSUE THREAD

**Issue by whiskyagogo** [nicolaisi/couchquery#7]
I'm using svn and sync_design_doc chokes on the .svn directories. More specifically, it creates a view with an empty name and no map or reduce functions. This results in a corrupted design doc.

I'd like to propose the following patch in couchquery/**init**.py starting at line 518:

> ```
>        for view in os.listdir(directory):
>            if view.startswith('.'):
>                continue
>            v = {}
> ```

**Comment by mikeal** [comment]
Go ahead and push that fix to your fork and I'll merge it.

**Comment by luftigdev** [comment]
I ran into the same problem. Syncing of views with svn directories does not work. Seems like this has not yet been fixed?

**Comment by nicolaisi** [comment]
https://github.com/mikeal/couchquery/pull/17 I included the code above in my pull request as well.

**Comment by nicolaisi** [comment]
Merged the fix
