### ISSUE TITLE
couchquery does not transmit user/password info to CouchDB

### ISSUE THREAD

**Issue by lstep** [nicolaisi/couchquery#8]
When setting a user/password in the uri (couchquery.createdb('http://admin:foobar@couchdb/callstats'), couchquery does not transmit user/password info to CouchDB

**Comment by nicolaisi** [comment]
You mean you cannot create the database? I ran the createdb and I got no error.

```
In [10]: db = couchquery.createdb('http://admin:foobar@localhost:5984/forms')

In [11]: couchquery.Database('http://ntj:nico@localhost:5984/forms')
Out[11]: <couchquery.Database at 0x1bf0dd0>
```
