### ISSUE TITLE
Option to add header parameter to specify extra headers when PUT/POSTing

### ISSUE THREAD

**Issue by lstep** [nicolaisi/couchquery#9]
There's a "bug" when using NGINX in front of CouchDB, and PUTs. NGINX requires a Content-Length, to accept the request. On other couchDB modules, an option to add an extra header has been added to correct this problem (which is not on couchquery's side, but more on NGINX's strictness).

See http://code.google.com/p/couchdb-python/issues/detail?id=130 or http://groups.google.com/group/couchrest/browse_thread/thread/ed0e251936b391ac for details of headers

**Comment by nicolaisi** [comment]
@istep, do you already solve this?
